version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: gomod
    directory: /e2e
    target-branch: dev
    schedule:
      interval: weekly
    groups:
      all:
        patterns: ["*"]
    ignore:
      - dependency-name: "k8s.io/*"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    groups:
      all:
        patterns: ["*"]
