{{- if and (eq .Values.storage.backend "disk") (not .Values.storage.emptyDir) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nx-k8s-cache.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nx-k8s-cache.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
