{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nx-k8s-cache.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nx-k8s-cache.labels" . | nindent 4 }}
{{- end }}
